//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomtSnor.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Login
    {
        public int LoginID { get; set; }
        public string LoginEmail { get; set; }
        public string LoginPassword { get; set; }
        public string LoginStatus { get; set; }
        public System.DateTime LoginCreationDate { get; set; }
        public int UserID { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_User tbl_User1 { get; set; }
    }
}
